backend:
  name: github
  repo: arcanexai/arcanex-site
  branch: main
  base_url: /.netlify/functions   # → /.netlify/functions/auth lesz hívva

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body",  name: "body",  widget: "markdown" }