backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"   # files saved in the repo
public_folder: "/uploads"        # how files are referenced on the site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body",  name: "body",  widget: "markdown" }